Documentation Update
NaomiProject/naomi-docs pull request #62
Opened 2021-01-21 18:32 UTC by mcoyne1948

Add detail about the Architectural Overview to the introduction. Looking for a little more detail on this topic.
Update Raspian to Rasberry Pi OS in the installation documentation

2021-01-23 03:08 UTC, aaronchantrill commented
These changes look good to me. Thanks for working on this. I'm going to ask @AustinCasteel to review.

2021-01-23 22:08 UTC, AustinCasteel requested changes
Changes look good and I have fixed the conflict except for the one line in rasppi that I flagged.

2021-01-23 22:08 UTC, AustinCasteel commented on installation/rasppi.md
> +To get Naomi up and running all you need to do is follow the steps described on the Naobian [download](/download/) page for RaspberryPi and the version you would like to use.
If you could remove the added "Naobian" since the download page is not just Naobian. (Also we need to update the Naobian image).

2021-01-25 22:02 UTC, AustinCasteel commented
How are you getting the error page, are you testing the docs locally or are you referring to the live site? From what I can tell it works properly on the site as well as in local testing.

2021-01-26 01:43 UTC, mcoyne1948 commented
> How are you getting the error page, are you testing the docs locally or are you referring to the live site? From what I can tell it works properly on the site as well as in local testing.

I think I must have been testing locally because I cannot reproduce. My problem is I still don't know how to comfortably navigate my way around git. Still not clear I have gotten the pull process figured out.

2021-01-26 19:26 UTC, merged